name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest]
        include:
          - os: macos-latest
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.11"
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Cache tox
        uses: actions/cache@v4
        with:
          path: .tox
          key: test-${{ hashFiles('pyproject.toml') }}

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      # these libraries enable testing on Qt on linux
      - uses: tlambert03/setup-qt-libs@v1.8

      - name: Install dependencies
        run: python -m pip install tox tox-gh-actions

      - name: Install Windows OpenGL
        if: runner.os == 'Windows'
        run: |
          git clone --depth 1 https://github.com/pyvista/gl-ci-helpers.git
          powershell gl-ci-helpers/appveyor/install_opengl.ps1

      # this runs the platform-specific tests declared in tox.ini
      - name: Test with tox
        uses: aganders3/headless-gui@v2
        with:
          run: python -m tox -v
        env:
          PLATFORM: ${{ matrix.os }}

      - name: Coverage
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.lcov
